# Generated by Django 4.2.18 on 2025-02-05 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_remove_item_name_item_title_alter_itemlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('doFirst', 'Do First'), ('schedule', 'Schedule'), ('delegate', 'Delegate'), ('eliminate', 'Eliminate')], default='doFirst', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, to='auth.User'),  # Ensure this default value is correct
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
