# Generated by Django 4.2.18 on 2025-02-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_item_priority_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('doFirst', 'Do First'), ('schedule', 'Schedule'), ('delegate', 'Delegate'), ('eliminate', 'Eliminate')], default='doFirst', max_length=20),
        ),
    ]
