# Generated by Django 4.2.18 on 2025-02-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_matrix',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='position_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='position_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(blank=True, choices=[('doFirst', 'Do First'), ('schedule', 'Schedule'), ('delegate', 'Delegate'), ('eliminate', 'Eliminate')], max_length=50, null=True),
        ),
    ]
