# Generated by Django 4.2.18 on 2025-02-02 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_item_itemlist_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.itemlist'),
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
