# Generated by Django 4.2.18 on 2025-02-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_item_user_alter_item_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='priority',
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
