# Generated by Django 4.2.18 on 2025-02-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_item_position_x_item_position_y_alter_item_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
